### ISSUE TITLE
PHP seems to have lost some highlighting in latest update

### ISSUE THREAD

**Issue by blakewatson** [joytrekker/rainier-syntax-theme#3]
In the update that recently hit the VS Code marketplace (which looks great by the way!) it seems that PHP lost some of it’s highlighting. Here’s a comparison:

<img width="734" alt="Screen Shot 2021-04-17 at 6 24 21 PM" src="https://user-images.githubusercontent.com/801425/115129366-cac38500-9faa-11eb-8bd4-6de04fa9be94.png">

<img width="761" alt="Screen Shot 2021-04-17 at 6 23 41 PM" src="https://user-images.githubusercontent.com/801425/115129369-d0b96600-9faa-11eb-908f-2576a623242b.png">

I don’t know if you use PHP much but I can help debug/test PHP's highlighting once this repo is up to date.

**Comment by joytrekker** [comment]
Thanks for letting me know. Currently I'm only working with python so any help with other languages is appreciated. I'll push out a fix tonight or tomorrow.

**Comment by joytrekker** [comment]
Pushed out an update. Let me know how it looks. All functions should be blue.

**Comment by blakewatson** [comment]
Between this fix and the other pull request I think we can close this issue. Looking forward to seeing this on the marketplace. 👍
